### ISSUE TITLE
loadstart and loadstop events

### ISSUE THREAD

**Issue by prantikv** [initialxy/cordova-plugin-themeablebrowser#104]
The plugin is super UI friendly and offers the same theme and experience to the user which is really nice.
I want to use the loadstart and loadstop events which are seen in the original inappbrowser plugin [here](https://www.npmjs.com/package/cordova-plugin-inappbrowser#inappbrowseraddeventlistener)

Is there any way to get this done.

-Thanks

**Comment by jibon57** [comment]
Sure you can.
```

var browser = cordova.ThemeableBrowser.open("example.com", {
   statusbar: {
         color: '#f53d3d'
    }, 
   ////
});
browser.addEventListener('loadstart', function(event){
//
});
browser.addEventListener('loadstop', function(event){
//
});
```
