### ISSUE TITLE
Can be installed from config.xml ?

### ISSUE THREAD

**Issue by kiskeh4ck** [initialxy/cordova-plugin-themeablebrowser#113]
For issues of build.phonegap (cloud) I need to install from the config.xml .. Can it be achieved?

The following line of text does not work for me:
`<plugin name="cordova-plugin-themeablebrowser" source="npm" spec="&gt;1.0.0" />`

**Comment by mvanhalen** [comment]
You need to add the following to the config.xml for Phonegap Build 

`<gap:plugin name="cordova-plugin-themeablebrowser" source="npm" />`

` <feature name="ThemeableBrowser">
    <param name="android-package" value="com.initialxy.cordova.themeablebrowser.ThemeableBrowser" />
    <param name="ios-package" value="CDVThemeableBrowser" />
  </feature>`

That works fine for me
