### ISSUE TITLE
How to integrate this plugin into ionic？

### ISSUE THREAD

**Issue by forsigner** [initialxy/cordova-plugin-themeablebrowser#12]
This plugin is awesome, is there somebody succeed to integrate this plugin into ionic?

**Comment by initialxy** [comment]
I haven't looked deeply into Ionic's docs yet. I can take a dive. Is there anything special I should be aware of?

**Comment by initialxy** [comment]
I have tested this plugin with Ionic. It works fine. I don't think there's anything special a Cordova plugin must do to be compatible with Ionic. I've inspected [ionic-plugins-keyboard](https://github.com/driftyco/ionic-plugins-keyboard)'s source code and there isn't much to note. If you are talking about [ngCordova](http://ngcordova.com/) then it's in ngCordova's author's interest to create wrappers. It should be quite straightforward to create a wrapper on your own.

**Comment by forsigner** [comment]
谢谢，I have solve this ploblem by some code as follow, although not elegant，but work，the elegant way is creating a wrapper.

```js
 var cordova = window.cordova;
``

By the way, are you a chinese?

**Comment by initialxy** [comment]
Awesome, good to know. Yeah I'm Chinese Canadian. I can read *some* Chinese.

**Comment by forsigner** [comment]
Cool~
