### ISSUE TITLE
How to open themeable browser within themeable browser

### ISSUE THREAD

**Issue by skhurams** [initialxy/cordova-plugin-themeablebrowser#13]
Hi again
i have three pages 1) index page 2) faqs page and 3) contactus page.
On index page i have a link which opens contactus page in themeable browser
Now in contactus page there is a hyperlink which suppose to open faqs page but currently its  not openning.
probably the themeable browser is already open i think. So how do i open themeable browser within a link in themeable browser

**Comment by skhurams** [comment]
and one more thing on exit the page is still in memory when i remote debug i still see the last page after exit or close.

**Comment by initialxy** [comment]
> and one more thing on close page is still in memory when i remote debug i still see the last page

@skhurams, could you please open a separate issue for this so that it can be tracked independently? Could you please also include the platform and version for this issue? (iOS, Android?)

Now back to your previous comment. If I understand this correctly, user opens the Contact Us page in ThemeableBrowser. While in ThemeableBrowser, user clicks on a URL in Contact Us that leads to FAQ. I assume this redirection happens entirely in ThemeableBrowser and your JavaScript (wrapped by Cordova) did not interact wit this redirection. Furthermore the URL of FAQ page on Contact Us page is correct and reachable. Is that correct? If that's the case then ThemeableBrowser should work by design. eg. If you load up Google, then click on Google News, ThemeableBrowser should redirect  you to Google News page. What you are trying to accomplish is analogical in behaviour is it?

You may want to add a listener to `loadstart`, `loadstop` and `loaderror` events to see if there's any loading errors.

**Comment by initialxy** [comment]
@skhurams, could you also include platform and version for this issue? (ie, iOS 7 etc.)

**Comment by initialxy** [comment]
By the way, did you use _blank for your FAQ URL in Contact Us? Because multi-window is totally not supported.

**Comment by skhurams** [comment]
yes i used target="_blank" but it didn't help

**Comment by initialxy** [comment]
What I meant was `target="_blank"` is **not** supported by neither ThemeableBrowser nor InAppBrowser. So if that's the case, then removing it will help. I assume you didn't have `target="_blank"` before?

What if you open your Contact Us page in your system's default browser eg.

    cordova.ThemeableBrowser.open('http://your-url/contactus', '_system');

Then you click on FAQ link in your system browser, does that work? What is the behaviour there? Do you use any frameworks for your Contact Us page eg. jQuery Mobile? Again, what's your platform and version?

**Comment by initialxy** [comment]
It would help if you could post the source code inside your Contact Us page that links to your FQA page. Of course, feel free to mask any confidential information.

**Comment by initialxy** [comment]
FYI I've made a new release to address memory leak issues. Note that on Android, memory is cleaned up by garbage collector, which doesn't come in that quickly. So you have to wait for about 10 seconds for the dismissed WebView to be destroyed.

**Comment by anilk533** [comment]
Hi How add loader or prograssbar in themebrowser i want to show  laoder in themebrowser untill its open www.google.com.for now its taking some time to open and untill it opens its showing empty white screen.

this is my code (ima using ionic)





$scope.themebrowser = function()
	 {
		          
						var ref = cordova.ThemeableBrowser.open('http://www.eenadu.net/andhra-pradesh-news.aspx', '_blank',
						{
							statusbar: {
							color: '#ffffffff'
						},
						toolbar: {
							height: 44,
							color: '#f0f0f0ff'
						},
						title: {
							color: '#003264ff',
							showPageTitle: true
						},
						backButton: {
							image: 'back',
							imagePressed: 'back_pressed',
							align: 'left',
							event: 'backPressed'
						},
						forwardButton: {
							image: 'forward',
							imagePressed: 'forward_pressed',
							align: 'left',
							event: 'forwardPressed'
						},
						closeButton: {
							image: 'close',
							imagePressed: 'close_pressed',
							align: 'right',
							event: 'closePressed'
						}
						/*,
						customButtons: [
						{
						image: 'share',
						imagePressed: 'share_pressed',
						align: 'right',
						event: 'sharePressed'
						}
						],
						menu: {
						image: 'menu',
						imagePressed: 'menu_pressed',
						title: 'Test',
						cancel: 'Cancel',
						align: 'right',
						items: [
						{
						event: 'helloPressed',
						label: 'Hello World!'
						},
						{
						event: 'testPressed',
						label: 'Test!'
						}
						]
						}*/
						,
						"browserProgress": {
						"showProgress": true,
						"progressBgColor": "#016585",
						"progressColor": "#FFAA16"
						},
						backButtonCanClose: true,
						fullscreen:true
						}).addEventListener('backPressed', function(e) {
							$ionicHistory.goBack();
						//alert('back pressed');
						}).addEventListener('helloPressed', function(e) {
						//alert('hello pressed');
						}).addEventListener('sharePressed', function(e) {
						//alert(e.url);
						}).addEventListener(cordova.ThemeableBrowser.EVT_ERR, function(e) {
							console.error(e.message);
						}).addEventListener(cordova.ThemeableBrowser.EVT_WRN, function(e) {
						//alert(e.message);
						});
						
						
						
						ref.addEventListener('loadstart', function(event) {
							console.log('loadstart');
							$ionicLoading.show({
							content: 'Loading',
							animation: 'fade-in',
							showBackdrop: true,
							maxWidth: 200,
							showDelay: 0
						  });
						//$scope.progressbar = ngProgressFactory.createInstance();
						//$scope.progressbar.start();
						});
						ref.addEventListener('loadstop', function(event) {
							$ionicLoading.hide();
						//alert('loadstop');
						//$scope.progressbar.stop();
						$ionicLoading.hide();
						});
						ref.addEventListener('event_getURL', function(event) {
						//alert('event_getURL');
						});
						ref.addEventListener('exit', function(event) {
						//alert('exit');
						});
						
						
		 
	 }



if add loader in on event load 'start' its not showing laoder in themble Browser its showing in my actuall view(before page)

how solve this please help me
