### ISSUE TITLE
toolbar at bottom

### ISSUE THREAD

**Issue by Blackscr33n** [initialxy/cordova-plugin-themeablebrowser#140]
Hey!

is it possible to set the toolbar to the bottom of the screen?

Greets

**Comment by marc7000** [comment]
Hi,

see:
https://github.com/initialxy/cordova-plugin-themeablebrowser/blob/master/README.md

> Two properties from InAppBrowser are disabled.
> 
> location is always false because address bar is not needed for an immersive experience of an integrated browser.
> toolbarposition is always top to remain consistent across platforms.
