### ISSUE TITLE
Cannot goback in ios

### ISSUE THREAD

**Issue by daoshenjay** [initialxy/cordova-plugin-themeablebrowser#154]
Hi，I open an angular2 page in the themeableBrowser(ios platform).And then I clicked a link goto another page.After that,back button is still gray in toolbar.So I cannot goto pre page by click it.

Angular2 goto another page by Anchor witch url like this:
http://www.demo.com/#/secondpage

Any suggestion for me? Thanks!

**Comment by daoshenjay** [comment]
OK，I resolved this myself.
1.Added an observer:
[[NSNotificationCenter defaultCenter] addObserver:self
                                         selector:@selector(webViewHistoryDidChange:)
                                             name:@"WebHistoryItemChangedNotification"
                                           object:nil];

2. Update buttons:
- (void)webViewHistoryDidChange
{
     [self updateButtons:self.webView];
}

**Comment by daoshenjay** [comment]
close this.

**Comment by hiepxanh** [comment]
hello mr @daoshenjay can you show me more detail where to add this? I'm facing the same issue and still cannot open the webpage
