### ISSUE TITLE
Button Options Not Working İos 11 And Android 7.0

### ISSUE THREAD

**Issue by emrekara37** [initialxy/cordova-plugin-themeablebrowser#156]
Hi , ThemeableBrowserOptions  not working ios 11 and android 7.0 not seen buttons

**Comment by demym** [comment]
Hi, i'm on IOS 10.0.2, but the ThemeableBrowserOptions are not working; i need the Close button, but it not showing even with these options:

{
        statusbar: {
          color: '#049a55'
        },
        toolbar: {
          height: 44,
          color: '#049a55'
        },
        title: {
          color: '#003264ff',
          showPageTitle: true
        },
        backButton: {
          image: 'back',
          imagePressed: 'back_pressed',
          align: 'left',
          event: 'backPressed'
        },
        forwardButton: {
          image: 'forward',
          imagePressed: 'forward_pressed',
          align: 'left',
          event: 'forwardPressed'
        },
        closeButton: {
          image: 'close',
          imagePressed: 'close_pressed',
          align: 'left',
          event: 'closePressed'
        }/*,
        customButtons: [
          {
            image: 'share',
            imagePressed: 'share_pressed',
            align: 'right',
            event: 'sharePressed'
          }
        ],
        menu: {
          image: 'menu',
          imagePressed: 'menu_pressed',
          title: 'Test',
          cancel: 'Cancel',
          align: 'right',
          items: [
            {
              event: 'helloPressed',
              label: 'Hello World!'
            },
            {
              event: 'testPressed',
              label: 'Test!'
            }
          ]
        }*/,
        backButtonCanClose: true,
        closebuttoncaption: "DONE",
        location: "yes"
      }


The same is working fine on Android.
On IOS is a problem, i cannot close the browser when loaded (no back button).

Can you help please ? Thanks very much in advance

**Comment by aaharutyunyan** [comment]
I have the same problem. Do you resolved it?

**Comment by arungkumar10** [comment]
This issue persistent but still there is no solution. If anybody knows tell me the solution. Thanks.

**Comment by fradali** [comment]
Hi, is there any solution for this problem or a workaround ? 
Thanks.
