### ISSUE TITLE
0.2.4 version will let ios no any response

### ISSUE THREAD

**Issue by bau720123** [initialxy/cordova-plugin-themeablebrowser#16]
hi @initialxy 
when I use PGB 3.7.1 and your plugin 0.2.4 version
Android will show a windows (a apache website content)
but in iOS 8.3
nothing happened (no any error message)

0.2.2 version is work well
the code just like your sample code

**Comment by initialxy** [comment]
Thanks for reporting this issue. This happens when custom buttons are defined but image resources are missing. I've fixed it with 0.2.5, please try it out.

**Comment by bau720123** [comment]
version 0.2.6 solve the problem
thanks
