### ISSUE TITLE
pinch or double tap to zoom not working

### ISSUE THREAD

**Issue by ricolo** [initialxy/cordova-plugin-themeablebrowser#17]
In cordova-plugin-inappbrowser, `enableViewportScale: 'yes'` enables pinch or double tap to zoom on iOS (while Android has this feature enabled by default and is not affected by this option value), however I can't have double tap to zoom either on iOS or Android in cordova-plugin-themeablebrowser even with this option on.

Should I expect zooming to be available in this plugin? I can't code in iOS but try to look into the iOS code. The variable `enableviewportscale` is still there. Thanks.

**Comment by initialxy** [comment]
This seems like an oversight on my part. I will fix it when I have time.

**Comment by ricolo** [comment]
Thank you so much, this is a really useful plugin. :+1:

**Comment by initialxy** [comment]
I've enabled zoom capability by default for both Android and iOS. Please try the latest release, 0.2.6.

**Comment by ricolo** [comment]
Works on both platforms, thank you! :smile:

**Comment by rocky1n** [comment]
awesome plugin ! but, how can i disable zoom, clear cache, session cache -  every time i open inappbrowser ? doesn't work the way it works for inappbrowser plugin on NPM ? kindly let me know?
