### ISSUE TITLE
How add button on toolbar or menu item

### ISSUE THREAD

**Issue by hungdalat** [initialxy/cordova-plugin-themeablebrowser#2]
Hi,

I have a question, how i can add a button on toolbar or menu item.

I am using themeablebrowser to open preview .docx file. I want add a button "download", share,..
Thank you so much!

**Comment by initialxy** [comment]
Hi,
Originally my requirement was to add a drop down menu that allows custom buttons to be added. This is where you could add custom actions. However I gave another thought to your concern and I figured what you want makes a lot of sense and it's not too hard for me to add such feature as long as I refactor my code. This is exactly what I did this weekend. Please see release 0.2.0 (available from Cordova Plugin Registry as well as github), where API was redesigned to be more elegant and ability to add custom buttons straight to the toolbar is added (see customButtons property). Thanks.
