### ISSUE TITLE
How to detect the back button of android?

### ISSUE THREAD

**Issue by ctl1690** [initialxy/cordova-plugin-themeablebrowser#21]
Because the back button always close the themeablebrowser window.
Does it possible to back previous page?
It not work when I set backButtonCanClose false.
And the last inappbrowser plugin can back to previous page.

**Comment by initialxy** [comment]
Looks like this is an [enhancement implemented by InAppBrowser after I forked their repo](https://github.com/apache/cordova-plugin-inappbrowser/commit/392a73c2cdcfc643622832cb6d2ac218f4da082a#diff-3668c67cd5f32235832f40e73cf5d4f0R51). I will consider making a merge. For now it is considered an enhancement.

**Comment by ctl1690** [comment]
Thanks a lot. 
I hope to merge as soon as possible.
This plugin will become very perfect !!

**Comment by initialxy** [comment]
Merged and released with 0.2.7.

**Comment by ctl1690** [comment]
Thanks a lot. Perfect !!!
