### ISSUE TITLE
[just a recommand] plugins.cordova.io will be deprecated in the near future

### ISSUE THREAD

**Issue by bau720123** [initialxy/cordova-plugin-themeablebrowser#23]
hi @initialxy 

according to these
http://phonegap.com/blog/2015/05/26/npm-plugins-available/
http://cordova.apache.org/announcements/2015/04/21/plugins-release-and-move-to-npm.html

so...just want to inform you that your plugin should be move to npm in the future...

**Comment by initialxy** [comment]
Thanks for bringing this to my attention. I will look into it.

**Comment by bau720123** [comment]
thanks @initialxy

**Comment by initialxy** [comment]
Done!

**Comment by bau720123** [comment]
Good Job @initialxy
