### ISSUE TITLE
iPad crash

### ISSUE THREAD

**Issue by ctl1690** [initialxy/cordova-plugin-themeablebrowser#24]
iPad can't click share and menu button.

*** Terminating app due to uncaught exception 'NSGenericException', reason: 'Your application has presented a UIAlertController (<UIAlertController: 0x7febcd1c69e0>) of style UIAlertControllerStyleActionSheet. The modalPresentationStyle of a UIAlertController with this style is UIModalPresentationPopover. You must provide location information for this popover through the alert controller's popoverPresentationController. You must provide either a sourceView and sourceRect or a barButtonItem.  If this information is not known when you present the alert controller, you may provide it in the UIPopoverPresentationControllerDelegate method -prepareForPopoverPresentation.'

**Comment by initialxy** [comment]
Fixed in version 0.2.9. Please note that due to [Cordova's migration to npm](http://cordova.apache.org/announcements/2015/04/21/plugins-release-and-move-to-npm.html), plugin ID has been updated to `cordova-plugin-themeablebrowser`.

**Comment by ctl1690** [comment]
Thanks. It's work.
