### ISSUE TITLE
Hardware Back Handling

### ISSUE THREAD

**Issue by amsimaganti** [initialxy/cordova-plugin-themeablebrowser#26]
HI
 First of all thanks a lot  for your awesome plugin.
 I wanted to show a confirmation box when users try to close this Themeable browser or hit hardware back button.Help me out

**Comment by initialxy** [comment]
Since this plugin is a fork of (InAppBrowser)[https://github.com/apache/cordova-plugin-inappbrowser], you can listen to events inherited from InAppBrowser. Notably, `exit` event. eg.

    cordova.ThemeableBrowser.open(...).addEventListener('exit', function() {
        ...
    });
