### ISSUE TITLE
clearcache & clearsessioncache does not work

### ISSUE THREAD

**Issue by 5uper** [initialxy/cordova-plugin-themeablebrowser#27]
hi @initialxy first thanks for the plugin
I try the options `clearcache` and `clearsessioncache` from inappbrowser, but unfortunately they do not work.

![bildschirmfoto 2015-06-15 um 16 48 25](https://cloud.githubusercontent.com/assets/2557532/8162771/af091572-137f-11e5-9260-a25c634d83a8.png)

**Comment by initialxy** [comment]
Try

    cordova.ThemeableBrowser.open(..., {
        ...
        clearcache: true,
        clearsessioncache: true,
        ...
    });

All properties are converted to JSON so boolean properties are now just boolean.

**Comment by 5uper** [comment]
ok thx this works,
I have an idea that you could also include, in inappbrowser of Facebook you can hide the inappbrowser by swipe down the toolbar.

**Comment by initialxy** [comment]
I will open a separate issue for this feature request, as it gets confusing in the bug tracker.

**Comment by liuya891012** [comment]
when the web page changes,I  can't see the change of web page in the app,And I try those options ,but  they do not work.
```
cordova.ThemeableBrowser.open(..., {
    ...
     reload:true,
     backButtonCanClose: true,
     clearcache: true,
    ...
});
```

**Comment by liuya891012** [comment]
when the web page changes,I  can't see the change of web page in the app,And I try those options ,but  they do not work.
```
cordova.ThemeableBrowser.open(..., {
    ...
     reload:true,
     clearsessioncache: true,
     clearcache: true,
    ...
});
```
