### ISSUE TITLE
Expanded wwwImage feature to toolbar ?

### ISSUE THREAD

**Issue by bau720123** [initialxy/cordova-plugin-themeablebrowser#28]
hi @initialxy 
according to this
https://github.com/initialxy/cordova-plugin-themeablebrowser/blob/master/RELEASENOTES.md
0.2.11 version seem can use "Expanded wwwImage feature to toolbar"
well...
If I have not misunderstood
if it mean can use the outside domain http address to define the pic

for example...
```
backButton: {
        image: 'http://www.littlebau.com/phonegap/images/back.png',
    },
```
but I tried...not work

**Comment by initialxy** [comment]
Two things:
1. The property name is **`wwwImage`**. `image` is reserved for loading from native resource bundle.
2. The URL for `wwwImage` is expected to be a relative path under the `www` directory of your application (where you'd place images for your HTML5 application), **not** a URL that reaches out to the world wide web. This is for performance, security and reliability reasons. eg. Your image could be placed under `<project dir>/www/images/toolbar.png` and you'd configure it as

    backButton: {
        wwwImage: 'images/toolbar.png',
    }

**Comment by bau720123** [comment]
hi @initialxy 
got it !!!
I will try for it
well...
just want to ask...can you give me some sample png (if you have some...) in order to help me add these to www folder ? XD

**Comment by initialxy** [comment]
This project contains some sample images that I use during development. See [here](https://github.com/initialxy/cordova-plugin-themeablebrowser/tree/master/src/android/res/drawable-xhdpi). All of these are x2 density.
