### ISSUE TITLE
how to use images

### ISSUE THREAD

**Issue by vespino** [initialxy/cordova-plugin-themeablebrowser#29]
I stumbled on your project and would like to incorporate it in mine. It's not clear to me how to implement the images (close, back, forward, etc). Do you have an example of howto using Phonegap Build?

**Comment by xlozinguez** [comment]
@vespino the answers are here https://github.com/initialxy/cordova-plugin-themeablebrowser#import-native-images

**Comment by initialxy** [comment]
@xlozinguez, thanks for your assistance. @vespino, the (strongly) recommended way to link image is to add images files to your native resource detailed by the link @xlozinguez posted.

That being said, I understand that Phonegap Build basically does not allow you to add native files. For this matter, we have issues: #11 and #25, which discusses work arounds. The gist is that I'd recommend taking advantage of Phonegap Build's private plugin feature to put your images resources in a private plugin, and install it along with your build.

That being said, I understand that Phonegap Build demands money if you want to use private plugin. For this matter, I have implemented an [experimental feature](https://github.com/initialxy/cordova-plugin-themeablebrowser#experimental-properties) that allows you to source your images from your `www` resource. (Also see issue #28) This feature is strongly discouraged, but if you must, go ahead.

**Comment by vespino** [comment]
I will look into it when I get the chance and meanwhile follow your project for updates on this issue.

**Comment by vespino** [comment]
Works great! Thanks. Now to find some iOS like images :) :+1:
