### ISSUE TITLE
ref.show() not working in ios

### ISSUE THREAD

**Issue by mahmud-vir** [initialxy/cordova-plugin-themeablebrowser#31]
I am trying to add spinner while loading content on browser. Its working fine on Android but on in iOS. The method 'show' not available on plugin.

**Comment by initialxy** [comment]
Thanks for letting me know. I will investigate.

**Comment by jackyon** [comment]
+1

**Comment by edison** [comment]
+1

**Comment by initialxy** [comment]
Fixed in version 0.2.12.

**Comment by edison** [comment]
Perfect! Thanks for this super plugin!
