### ISSUE TITLE
Need Help with JavaScript Object

### ISSUE THREAD

**Issue by akriger** [initialxy/cordova-plugin-themeablebrowser#38]
I have added a custom button that, when clicked, closes the IAB and opens the barcode scanner which in return once something is scanned will open IAB again to what was scanned. The problem is after the first scan the button no longer works. The only way I found it to work  multiple times is it copy/paste the code over and over again into the .addEventListener. This is not ideally what I want. Is there anyway around the copy/past method?

**Comment by initialxy** [comment]
Hi, could you please elaborate on what you mean by the button no longer works? Do you mean themeable browser does not pop up once you call `ref.show()` or themeable browser does show up but your custom button does not respond?

**Comment by akriger** [comment]
Here is the scenario

You press button on app and themeable browser shows. They then press the custom barcode button, themeable browser closes and then the scanner shows. You scan upc and themeable browser opens again with the upc results. Then you press custom barcode button to scan another upc but it does not do anything. 
 
Is there a way I can show you my code without pasting it here

**Comment by initialxy** [comment]
I'm interested in finding out the sequence of calls you make to themeable browser. Github no longer has private message feature and I'm reluctant at posting my private email in the public (even though its in my git commits). So let's take another stub at it. I assuming your code looks something like this

    var ref = cordova.ThemeableBrowser.open(url, {
        ...
        customButtons: [
            {
                event: 'scan',
                ...
            }
        ],
        ...
    }).addEventListener('scan', function() {
        ref.close();

        cordova.plugins.barcodeScanner.scan(
            function(result) {
                ref = cordova.ThemeableBrowser.open(url, {
                    // FIXME: copy and paste?
                }).addEventListener('scan', function() {
                    // FIXME: copy and paste?
                    ...
                });
            },
            ...
        );
    });

Is that about right?

**Comment by akriger** [comment]
Yes that is correct if I copy/paste it 5 times it will work 5 times then quit working. Is there a way to "loop" the last event listener to start it back at the top of the original?

**Comment by initialxy** [comment]
When themeable browser is closed, all of its data is released for garbage collection, which keeps your app from blowing up the device's memory. So the simple solution is to reassign the listener. You just need refactor your code more elegantly. I don't want to dictate how you should dictate how you architecture your code, but try something like this

    var BROWSER_THEME = {
        ...
        customButtons: [
            {
                event: 'scan',
                ...
            }
        ],
        ...
    };

    function launchBrowserForBarcodeScanner(url) {
        var ref = cordova.ThemeableBrowser.open(
            url, BROWSER_THEME
        ).addEventListener('scan', function() {
            ref.close();

            cordova.plugins.barcodeScanner.scan(
                function(result) {
                    // TODO: Something with result
                    launchBrowserForBarcodeScanner(somethingToDoWithScanResult);
                },
                ...
            );
        });
    }

**Comment by akriger** [comment]
i misread your post about the copy/pasting.. But to give you an idea of my code I will just paste it here and take out some snippets


 $scope.startScanner = function(){
      
      cordova.plugins.barcodeScanner.scan(
        function (result) {
            var textFormats = "QR_CODE DATA_MATRIX";
            var productFormats = "UPC_E UPC_A EAN_8 EAN_13";

            if (result.cancelled) {
                return;
            }
            //alert("Scanned Code: " + result.text + ". Format: " + result.format);
            if (textFormats.match(result.format)) {                
                var scanVal = result.text;
                if (scanVal.indexOf("http") === 0) {
                    navigator.notification.confirm(
                            '(1) Open in Browser\n(2) Cancel',
                            function (b) {
                                if (b === 1) {
                                    cordova.ThemeableBrowser.open(scanVal, '_blank', {
                    statusbar: {
                        color: '#000000'
                    },
                    toolbar: {
                        height: 44,
                        color: '#000000'
                    },
                    title: {
                        color: '#ffffff',
                        showPageTitle: true
                    },
                    backButton: {
                        wwwImage: 'images/arrow-left-c.png',
                        wwwImagePressed: 'images/arrow-left-c-pressed.png',
                        wwwImageDensity: 3,
                        align: 'left',
                    },
                    forwardButton: {
                        wwwImage: 'images/arrow-right-c.png',
                        wwwImagePressed: 'images/arrow-right-c-pressed.png',
                        wwwImageDensity: 3,
                        align: 'left',
                    },
                    closeButton: {
                        wwwImage: 'images/close-round.png',
                        wwwImagePressed: 'images/close-round-pressed.png',
                        wwwImageDensity: 3,
                        align: 'right',
                    },
                    backButtonCanClose: true
                });
                                }
                            },
                            result.text,
                            '1, 2'
                    );
                } else {
                    navigator.notification.alert(
                            result.text,
                            function (){},
                            'Scan Value:',
                            'Done'
                        );
                }
            } else if (productFormats.match(result.format)) {
                //alert("Found Product Code: " + result.text  + ". Format: " + result.format);
                navigator.notification.confirm(
                        '(1) Look Up Product\n(2) Cancel',
                        function (b) {
                            if (b === 1) {
                                var searchUrl = "my url" + result.text;
                                var ref = cordova.ThemeableBrowser.open(searchUrl, '_blank', {
                    statusbar: {
                        color: '#000000'
                    },
                    toolbar: {
                        height: 44,
                        color: '#000000'
                    },
                    title: {
                        color: '#ffffff',
                        showPageTitle: true
                    },
                    backButton: {
                        wwwImage: 'images/arrow-left-c.png',
                        wwwImagePressed: 'images/arrow-left-c-pressed.png',
                        wwwImageDensity: 3,
                        align: 'left',
                    },
                    forwardButton: {
                        wwwImage: 'images/arrow-right-c.png',
                        wwwImagePressed: 'images/arrow-right-c-pressed.png',
                        wwwImageDensity: 3,
                        align: 'left',
                    },
                    closeButton: {
                        wwwImage: 'images/close-round.png',
                        wwwImagePressed: 'images/close-round-pressed.png',
                        wwwImageDensity: 3,
                        align: 'right',
                    },
                    customButtons: [
                        {
                            wwwImage: 'images/barcode.png',
                            wwwImagePressed: 'images/barcode-pressed.png',
                            wwwImageDensity: 3,
                            align: 'right',
                            event: 'barcodePressed'
                        }
                    ],
                    backButtonCanClose: true
                }).addEventListener('barcodePressed', function(e) {
                    ref.close();
							
                })
                    
                            }
                        },
                        result.text,
                        '1, 2' 
                ); 
            } else {
                alert("Scan format : " + result.format + 
                      " not supported. Scan value: " + result.text);
            }
        }); 

    };


now at the last bit of the code you will see that I have ref.close() as the eventlistener which is where the button no longer works. So i can take the code from cordova.plugins.barcodeScanner.scan down and copy paste that again after that ref.close(). The more I copy/paste that the longer the button works until it reaches the end of the copy/paste code. How do I avoid having to copy/paste

**Comment by initialxy** [comment]
Why not call `$scope.startScanner()` following `ref.close()`? eg.

    ...
    .addEventListener('barcodePressed', function(e) {
        ref.close();
        $scope.startScanner();
    });

Is there a problem with that?

**Comment by akriger** [comment]
When I first read put $scope.startScanner() I was like I already tried that. But now that I think about it i had just put 

...
.addEventListener('barcodePressed', function(e) {
    ref.close();
    startScanner();
});

without the $scope in front. Dummy me. This is working just like I needed thank you so much. Love your plugin.
