### ISSUE TITLE
iOS share button not working

### ISSUE THREAD

**Issue by vespino** [initialxy/cordova-plugin-themeablebrowser#44]
I'm using this plugin in combination with this plugin: https://build.phonegap.com/plugins/1197. In Android the sharing popup is shown when clicking on "sharePressed" but iOS doesn't show it. 

		}).addEventListener('sharePressed', function(e) {
			window.plugins.socialsharing.share('', 'Gedeeld via de app van Pannenkoekenhuizen', 'www/icon.png', e.url);
		});

Can this be themeablebrowser or SocialSharing?

**Comment by initialxy** [comment]
This is a bug on SocialSharing-PhoneGap-Plugin's side. In fact, [here is the line](https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin/blob/ac66d5d2d6faeb39a84ca09e81f6bf952aabea27/src/ios/SocialSharing.m#L117) that causes this problem. There is a very similar issue on [cordova-plugin-dialogs](https://github.com/jcesarmobile/cordova-plugin-dialogs) that's been discussed in issue #32, [here](https://issues.apache.org/jira/browse/CB-9441) and [here](https://issues.apache.org/jira/browse/CB-9347). Just to clarify, SocialSharing-PhoneGap-Plugin and cordova-plugin-dialogs are two unrelated plugins. Fixing cordova-plugin-dialogs will not help fix SocialSharing-PhoneGap-Plugin. However given the same nature of issue, the pull request for [CB-9347](https://issues.apache.org/jira/browse/CB-9347) can almost entirely get copied and pasted to SocialSharing-PhoneGap-Plugin and it will work.
