### ISSUE TITLE
Image import plugin for ThemeableBrowser

### ISSUE THREAD

**Issue by ingageco** [initialxy/cordova-plugin-themeablebrowser#54]
@initialxy - First of all, this plugin looks fantastic. 

As someone who uses Phonegap Build and also someone who is not too familiar with Cordova and custom plugins, I found your documentation on native images difficult to understand. I understand why you don't want to include the images, but I disagree with your thought that they are not needed. In my case, the default InAppBrowser looks terrible on Android, and I couldn't find a way to simply make it look better. That's where your plugin appealed to me - its a massive visual improvement on Android to the default InAppBrowser.

So in my case - I just wanted to use your plugin WITH the images, and I think there may me more like me. So I have attempted to create a custom plugin that imports your images as you described in issue #11 and would like to make it easily available to others using this if they'd like to use your default images. 

Here's the repo: https://github.com/ingageco/cordova-plugin-themeablebrowserimages

Thoughts?

**Comment by ingageco** [comment]
Also - I have no idea if this actually works. It's my first shot at creating a Cordova plugin. I'm in the process of testing.

**Comment by ingageco** [comment]
It works!

**Comment by sencenan** [comment]
Congratz.
