### ISSUE TITLE
Opening links from within inappbrowser

### ISSUE THREAD

**Issue by vespino** [initialxy/cordova-plugin-themeablebrowser#55]
I'm looking for a way to open the native browser from within the inappbrowser. In my app the following works fine, but when using this code inside the inappbrowser, the link simply opens inside the inappbrowser:

    <a href="#" onclick="window.open(url, '_system', 'location=yes')">Open</a>

Is there a work around that works cross platform? I thought of using browser:// but apparently this doesn't exist like eg twitter://

Help?

**Comment by initialxy** [comment]
The issue here is that the web pages loaded inside themeablebrowser is expected to be an arbitrary external site, so themeablebrowser does not load any Cordova plugins inside this isolated environment. What you need to do is to take advantage of the [`loadstart` event](https://cordova.apache.org/docs/en/3.0.0/cordova_inappbrowser_inappbrowser.md.html#addEventListener) to listen to some special URLs that you are interested in from **your app**, and launch system browser from **your app**. (Yeah I should port the docs over from InAppBrowser instead of "inherited from InAppBrowser" thing.) eg. You can say put

    <a href="#" onclick="window.open('specialprotocal://' + encodeURI(url))">Open</a>

Then in your app, open any URL that's prefixed with `'specialprotocal'` in system browser (don't forget to URL decode).

**Comment by vespino** [comment]
Could you give me an example because things like safari:// and browser:// don't work in iOS.

**Comment by aaslun** [comment]
Here's an example of how I solved this:

	var tb = cordova.ThemeableBrowser.open(url, '_blank', { ... });
	tb.addEventListener('loadstart', function(e) {
		
		// Check if url contains 'some_string' and open in system browser if so	
		if(e.url.indexOf('some_string') > -1) {
			tb.ThemeableBrowser.open(e.url, '_system');
			tb.close(); // Interrupt and close the current tb-view, it will continue to try to load the e.url otherwise
		        app.launchStartPage(url); // This method is declared elsewhere, and just starts a new instance of themeablebrowser
		}
	}

**Comment by vespino** [comment]
@aaslun I set tb.close() first to let it work in iOS. Now it works on Android and iOS, thanks! Now if I could only remember how to test my app for Windows Phone...

**Comment by anilk533** [comment]
Hi How add loader or prograssbar in themebrowser i want to show  laoder in themebrowser untill its open www.google.com.for now its taking some time to open and untill it opens its showing empty white screen.

this is my code (ima using ionic)





$scope.themebrowser = function()
	 {
		          
						var ref = cordova.ThemeableBrowser.open('http://www.eenadu.net/andhra-pradesh-news.aspx', '_blank',
						{
							statusbar: {
							color: '#ffffffff'
						},
						toolbar: {
							height: 44,
							color: '#f0f0f0ff'
						},
						title: {
							color: '#003264ff',
							showPageTitle: true
						},
						backButton: {
							image: 'back',
							imagePressed: 'back_pressed',
							align: 'left',
							event: 'backPressed'
						},
						forwardButton: {
							image: 'forward',
							imagePressed: 'forward_pressed',
							align: 'left',
							event: 'forwardPressed'
						},
						closeButton: {
							image: 'close',
							imagePressed: 'close_pressed',
							align: 'right',
							event: 'closePressed'
						}
						/*,
						customButtons: [
						{
						image: 'share',
						imagePressed: 'share_pressed',
						align: 'right',
						event: 'sharePressed'
						}
						],
						menu: {
						image: 'menu',
						imagePressed: 'menu_pressed',
						title: 'Test',
						cancel: 'Cancel',
						align: 'right',
						items: [
						{
						event: 'helloPressed',
						label: 'Hello World!'
						},
						{
						event: 'testPressed',
						label: 'Test!'
						}
						]
						}*/
						,
						"browserProgress": {
						"showProgress": true,
						"progressBgColor": "#016585",
						"progressColor": "#FFAA16"
						},
						backButtonCanClose: true,
						fullscreen:true
						}).addEventListener('backPressed', function(e) {
							$ionicHistory.goBack();
						//alert('back pressed');
						}).addEventListener('helloPressed', function(e) {
						//alert('hello pressed');
						}).addEventListener('sharePressed', function(e) {
						//alert(e.url);
						}).addEventListener(cordova.ThemeableBrowser.EVT_ERR, function(e) {
							console.error(e.message);
						}).addEventListener(cordova.ThemeableBrowser.EVT_WRN, function(e) {
						//alert(e.message);
						});
						
						
						
						ref.addEventListener('loadstart', function(event) {
							console.log('loadstart');
							$ionicLoading.show({
							content: 'Loading',
							animation: 'fade-in',
							showBackdrop: true,
							maxWidth: 200,
							showDelay: 0
						  });
						//$scope.progressbar = ngProgressFactory.createInstance();
						//$scope.progressbar.start();
						});
						ref.addEventListener('loadstop', function(event) {
							$ionicLoading.hide();
						//alert('loadstop');
						//$scope.progressbar.stop();
						$ionicLoading.hide();
						});
						ref.addEventListener('event_getURL', function(event) {
						//alert('event_getURL');
						});
						ref.addEventListener('exit', function(event) {
						//alert('exit');
						});
						
						
		 
	 }



if add loader in on event load 'start' its not showing laoder in themble Browser its showing in my actuall view(before page)

how solve this please help me

**Comment by vespino** [comment]
This works for me with inappbrowser, something similar works for themable browser. Just wanted to let you know:

    var ref = window.open(url, '_blank', 'toolbarposition=top,location=no');

    ref.addEventListener('loadstart', function(e) {
        if(e.url.indexOf('system_browser')>-1) {
            ref.close();
            window.open(e.url, '_system');
        }
    });
