### ISSUE TITLE
Unable to install plugin, getting 404 error

### ISSUE THREAD

**Issue by hriziya** [initialxy/cordova-plugin-themeablebrowser#58]
Hi, I am trying this command to add this plugin. but getting error.

    cordova plugin add cordova-plugin-themeablebrowser

This is what I am seeing in command prompt. 

    Fetching plugin "cordova-plugin-themeablebrowser" via plugin registry
    Error: 404 Not Found: cordova-plugin-themeablebrowser

**Comment by sirajulm** [comment]
Hi,
I too got the same error, you could do the same using

    cordova plugin add  https://github.com/initialxy/cordova-plugin-themeablebrowser.git
