### ISSUE TITLE
Invalid JSON @s when passing parameters

### ISSUE THREAD

**Issue by Samnan** [initialxy/cordova-plugin-themeablebrowser#64]
This is my code:

var url = "....."; // anything valid url here
        cordova.ThemeableBrowser.open(url, '_blank', {
          toolbar: {
            height: 44,
             color: "#ff0000ff"
          }
       });

I always get an empty white toolbar at the top of the browser. I looked at the console and it shows this:

11-05 12:26:29.319: I/chromium(31746): [INFO:CONSOLE(149)] "Invalid JSON @s", source: file:///android_asset/www/js/main.js (149)

followed by other messages like back button is not defined etc.

Other plugins are simple file, device, whitelist.. nothing that could cause problem..

using cordova 5 latest version... Whats is wrong?

**Comment by sencenan** [comment]
have you tried to config the "backButton" ?

**Comment by ryaa** [comment]
In my case, i got the above error because I had some props in options object commented in my code. Please make sure to remove any comments from options object
