### ISSUE TITLE
Make work refresh custom button

### ISSUE THREAD

**Issue by noveweb** [initialxy/cordova-plugin-themeablebrowser#66]
I've added a custom reload button, but i don't know how make it work.

Help Please!

**Comment by krisidmisso** [comment]
can you please help me or direct me how to add an image to buttons?? im not able to do it from the description of the plugin.
i added the file to each folder, xhdpi, xxhdpi... and referenced it as image: "back" and "back.png". none works

**Comment by noveweb** [comment]
Use themeable browser plugin together.
Em 18/01/2016 16:10, "krisidmisso" <notifications@github.com> escreveu:

**Comment by krisidmisso** [comment]
sorry to bother you again. i just installed inapp browser and recompiled my app but it still didnt show any buttons. I am leaving image: 'menu' and other options as in default and using cordova.ThemeableBrowser.open to open windows.

i dont know how to contact you other way but i promise i will delete these comments after I am done.

thanks in advance

**Comment by noveweb** [comment]
Hi, Guy!

In your config.xml use:
----------------------------------
<gap:plugin name="cordova-plugin-themeablebrowser" source="npm" />
<gap:plugin name="com.ingage.themeablebrowserimages" spec="0.1.0"
source="pgb" />
----------------------------------
In your script use:
-------------------------------------
 cordova.ThemeableBrowser.open(url, '_blank', {
    statusbar: {
        color: '#00000000'
    },
    toolbar: {
        height: 44,
        color: '#B32330'
    },
    title: {
        color: '#ffffffff',
        staticText: titulo,
        showPageTitle: true
    },
    backButton: {
        wwwImage: 'res/browser/back_button.png',
        wwwImagePressed: 'res/browser/back_button_pressed.png',
        wwwImageDensity: 4,
        align: 'left'
    },
    forwardButton: {
        wwwImage: 'res/browser/foward_button.png',
        wwwImagePressed: 'res/browser/foward_button_pressed.png',
        wwwImageDensity: 4,
        align: 'left'
    },
    closeButton: {
        wwwImage: 'res/browser/close_button.png',
        wwwImagePressed: 'res/browser/close_button_pressed.png',
        wwwImageDensity: 4,
        align: 'left'
    },
    customButtons: [

    ],

    backButtonCanClose: false
}).addEventListener(cordova.ThemeableBrowser.EVT_ERR, function(e) {
    console.error(e.message);
}).addEventListener(cordova.ThemeableBrowser.EVT_WRN, function(e) {
    console.log(e.message);
});
------------------------------------------

Good luck and Success!


2016-01-18 16:34 GMT-03:00 krisidmisso <notifications@github.com>:

> sorry to bother you again. i just installed inapp browser and recompiled
> my app but it still didnt show any buttons. I am leaving image: 'menu' and
> other options as in default and using cordova.ThemeableBrowser.open to open
> windows.
>
> i dont know how to contact you other way but i promise i will delete these
> comments after I am done.
>
> thanks in advance
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/initialxy/cordova-plugin-themeablebrowser/issues/66#issuecomment-172630494>
> .
>



--

**Comment by sencenan** [comment]
it appears that the :customButtons" section is not specified. 

```
customButtons: [
   {
        // button definition goes here
   }
]
```
