### ISSUE TITLE
not building with cordova-ios 4.0.1

### ISSUE THREAD

**Issue by bau720123** [initialxy/cordova-plugin-themeablebrowser#69]
hi @initialxy 
all detail right here
https://github.com/dpa99c/cordova-diagnostic-plugin/issues/27
this is why "cordova-plugin-themeablebrowser" also have this error too

developer should be follow this in iOS@4.0.1
http://cordova.apache.org/announcements/2015/12/08/cordova-ios-4.0.0.html

**Comment by olexme** [comment]
@bau720123 @initialxy - created PR for this issue https://github.com/initialxy/cordova-plugin-themeablebrowser/pull/73

**Comment by bau720123** [comment]
thanks @olexme 
but I think @initialxy seem not maintain this project for a long time
so...
maybe I should use yours to instead ?
https://github.com/olexme/cordova-plugin-themeablebrowser

**Comment by wal-nadeem** [comment]
@olexme Thanks a lot for this PR. A perfect solution. Works great. (y)

**Comment by olexme** [comment]
The project is really great and better than the original one (at least for me). It would be a big loss for the community to stop maintaining it. I hope @sencenan will eventually take care of all PRs like it was announced here https://github.com/initialxy/cordova-plugin-themeablebrowser/issues/75. Fingers crossed!

**Comment by sencenan** [comment]
Please try 0.2.14
