### ISSUE TITLE
Custom Button dont show in themeablebrowser

### ISSUE THREAD

**Issue by skhurams** [initialxy/cordova-plugin-themeablebrowser#7]
Hi I want to add custom button but its now showing can you please help heres the code

    function innAppInit(_url) {
      app.Log('browser news link=' + _url);
       if (_url == null) {
          _url = 'http://apache.org';
         }
       var ref = cordova.ThemeableBrowser.open(_url, '_blank', {

        backButtonCanClose: false,
        hideForwardButton: true,
        toolbarColor: '#239EC9',
        titleColor: '#FFFFFF',
        statusbarColor: '#239EC9',
        navButtonAlign: 'left',
        closeButtonAlign: 'right',

        titleStaticText: 'Add New Web Page',
        customButtons: [{
            image: 'themeablebrowser_stub_close',
            imagePressed: 'themeablebrowser_stub_close_highlight',
            align: 'right',
            event: 'customButtonPressed'
        }],
        menuButtonImage: 'themeablebrowser_stub_menu',
        menuButtonPressedImage: 'themeablebrowser_stub_menu_highlight',
        closeButtonImage: 'themeablebrowser_stub_close',
        closeButtonPressedImage: 'themeablebrowser_stub_close_highlight',
        backButtonImage: 'themeablebrowser_stub_back',
        backButtonPressedImage: 'themeablebrowser_stub_back_highlight',

    });
    ref.addEventListener('customButtonPressed', function(event) {
        alert(event.url);
    });
    ref.addEventListener('loadstart', function(event) {
        try {
            app.Log('loadstart function');
            $('.ui-loader').show();

        } catch (e) {
            app.ErrorLog(e);
        }
    });
    ref.addEventListener('loadstop', function(event) {
        try {
            app.Log('loadstop function');
            $('.ui-loader').hide();

            ref.executeScript({
                    code: 'return document.title'
                },
                function(values) {
                    alert(values);
                });

        } catch (e) {
            app.ErrorLog(e);
        }
    });
    ref.addEventListener('event_getURL', function(event) {
        try {

            var url = event.url;
            app.Log('get url=' + url);
            ref.close();

        } catch (e) {
            app.ErrorLog(e);
        }
    });
    ref.addEventListener('exit', function(event) {
        try {
            app.Log('exit function');

            $('.ui-loader').hide();

        } catch (e) {
            app.ErrorLog(e);
        }
    });
   }

**Comment by initialxy** [comment]
Hi there, I haven't run this code but I see a couple of issues in your code.

1. You are using the older API decide with a mostly flat property list. If that's working for you then you are definitely on an older version. Please make sure to update your plugin to the latest version. Try to run `cordova plugin update com.initialxy.cordova.themeablebrowser` and make sure it prints out 0.2.1 as version.
2. If you are on the latest version, then `themeablebrowser_stub_.*` images are no longer imported to your project. They are still found in source for sample and dev purpose, so if you really want to use them you can manually import them. But I suspect they are not found in your native resource. Please refer to the **Import Native Image** guide in README.md to make sure the images you are using are actually imported to native resource.
3. Back to point 1, please make sure you rearrange your properties for the new API.

Please investigate based on the above points. If issue still persists, please let me know which platform this issue happens (iOS, Android) and which version of plugin you have installed (see `<cordova_project_root>/plugins/com.initialxy.cordova.themeablebrowser/plugin.xml`.

Thanks!

**Comment by skhurams** [comment]
thanks for your help 
yes you were right it was old version . I am using cordova 3.7 , jqm 1.4.5,  Xcode 6.1 and  IOS
I have removed old version and installed new version but my existing code is not running 
its saying this 
CDVPlugin class CDVThemeableBrowser (pluginName: ThemeableBrowser) does not exist.
2015-03-31 20:28:09.652 WMC[32521:133526] ERROR: Plugin 'ThemeableBrowser' not found, or is not a CDVPlugin. Check your plugin mapping in config.xml.
2015-03-31 20:28:09.652 WMC[32521:133526] -[CDVCommandQueue executePending] [Line 158] FAILED pluginJSON = [
  "ThemeableBrowser423389274",
  "ThemeableBrowser",
  "open",
  [
    "https:\/\/www.google.com\/",
    "_blank",
    "{\"backButtonCanClose\":false,\"hideForwardButton\":true,\"toolbarColor\":\"#239EC9\",\"titleColor\":\"#FFFFFF\",\"statusbarColor\":\"#239EC9\",\"navButtonAlign\":\"left\",\"closeButtonAlign\":\"right\",\"menuButtonAlign\":\"right\",\"titleStaticText\":\"Add New Web Page\"}"
  ]
]

**Comment by initialxy** [comment]
It sounds like the plugin didn't install properly by Cordova. Try just uninstall and install it again. is:

    cordova plugin rm com.initialxy.cordova.themeablebrowser
    cordova plugin add com.initialxy.cordova.themeablebrowser

**Comment by initialxy** [comment]
Though you shouldn't have to manually add the feature tag in config.xml. Cordova command line should have taken care of that for you. Did you install this plugin manually by hand? If that's the case, the error sounds like the objective-c source code for iOS is not added. Make sure they are added to your xcode.

**Comment by skhurams** [comment]
No i didnt installed manually.  Actually cli has added tag in config.xml but the images were not showing so i copied images and placed in xcode resource folder now everything is working. thanks for the help 
Please close this thread

**Comment by initialxy** [comment]
I finally ran into this issue myself, and it certainly is a Cordova plugin installation issue. However being a very obsessed individual, I debugged Cordova's source code and found the issue in [node-xcode](https://github.com/alunny/node-xcode)'s code. I have raised an [issue](https://github.com/alunny/node-xcode/issues/44) at node-xcode and proposed a fix by creating a [pull request](https://github.com/alunny/node-xcode/pull/45). I have added details to [this issue](https://issues.apache.org/jira/browse/CB-5454) on Cordova's bug tracker as well.

The work around that I have proposed is to open the project in Xcode, navigate to YourProject -> Build Phases -> Compiled Sources, and manually add the missing plugin source file there (ThemeableBrowser.m).

**Comment by roop0001** [comment]
Hi, 

I am using ThemeableBrowser plugin for android app. I am using custom button. I am unable to set image to button. It is transparent but button click is handlable.

var url = "www.google.com";

   cordova.ThemeableBrowser.open(url, '_blank', {

            customButtons: [
                        {
                            image: 'ỉmg/phone-receiver.png',
                            align: 'left',
                            event: 'toolbarPressed'
                        }
            ],

            toolbar: {
                height: 44,
                event: 'toolbarPressed',
                color: '#FF0000'
            },
            title: {
                color: '#FFFFFF',
                showPageTitle: false,
                staticText:"Kritische storing? Bel ons nu!"
            },

            backButtonCanClose: false
        }).addEventListener('toolbarPressed', function(e) {

        console.error(e.message);
           var ref = window.open('tel:+31620450159');

        }).addEventListener(cordova.ThemeableBrowser.EVT_ERR, function(e) {
            console.error(e.message);
        }).addEventListener(cordova.ThemeableBrowser.EVT_WRN, function(e) {
            console.log(e.message);
        });
