### ISSUE TITLE
not building in cordova 6.0.0 with phonegap

### ISSUE THREAD

**Issue by skyblue89** [initialxy/cordova-plugin-themeablebrowser#79]
when try to build launch some error of incompatibility

**Comment by mobillytics** [comment]
Same here. Error messages I'm getting are:

../Plugins/cordova-plugin-themeablebrowser/CDVThemeableBrowser.m:72:19: error: no visible @interface for 'CDVPlugin' declares the selector 'initWithWebView:'
    self = [super initWithWebView:theWebView];
            ~~~~~ ^~~~~~~~~~~~~~~
../platforms/ios/AscentPortfolio/Plugins/cordova-plugin-themeablebrowser/CDVThemeableBrowser.m:320:31: error: no known instance method for selector 'URLIsWhitelisted:'
    if ([self.commandDelegate URLIsWhitelisted:url]) {

**Comment by mobillytics** [comment]
Did some research on this. It doesn't look like a easy fix. See below fixes for another plugin on the same issue: 
https://github.com/Wizcorp/phonegap-facebook-plugin/issues/1199

**Comment by sencenan** [comment]
Please test the fix.

**Comment by Sundved** [comment]
Build has been successful but my custom buttons dissapear from ios application :(

**Comment by sencenan** [comment]
@Sundved  cordova 6.0+ has a different asset folder structure. Make sure your resources are listed in the plist file correctly

**Comment by Sundved** [comment]
@sencenan Thank you, I forgot add my resources( But I think this [line](https://github.com/initialxy/cordova-plugin-themeablebrowser/commit/87747ff1869acb92135351a67fefb51711bd6500#diff-8735a5ebd29fa34402fa0f71411c6a08R338) need to fix with openInThemeableBrowser method

**Comment by sencenan** [comment]
good find. I will patch in.
