### ISSUE TITLE
how to implement it with ionic 2

### ISSUE THREAD

**Issue by kelvinrolex** [initialxy/cordova-plugin-themeablebrowser#87]
Pls i have added it to my ionic 2 project but i really don't know how to import it into the typescript. pls help me.

**Comment by sencenan** [comment]
Not an issue.

Please try stackoverflow for more generic help.

**Comment by vaibsVB** [comment]
@kelvinrolex 
I imported it as like this
`import { ThemableBrowser } from 'ionic-native';`

but I'm not able to change the buttons or toolbar.
Let me if you found any solutions.
