### ISSUE TITLE
How to disable animation effect in themeablebrowser

### ISSUE THREAD

**Issue by skhurams** [initialxy/cordova-plugin-themeablebrowser#9]
Hi I am showing themeablebrowser on page load the problem is i want to show tbrowser without animation. because first page is shown and then tbrowser is animatedly visible.
so how do i disable animation effect

**Comment by initialxy** [comment]
Neither ThemeableBrowser nor [InAppBrowser](https://github.com/apache/cordova-plugin-inappbrowser) support such feature, hence this is a feature request.

However judging by the code, it's a rather simple change, so I implemented it anyways. However I'm in the middle of preparing for the next release so I'm not gonna make a release just for this feature. You can install it by git revision. eg.

    cordova plugin add https://github.com/initialxy/cordova-plugin-themeablebrowser#c4900b9c36cefa82042f766c3c047f27e0a98fee

**Comment by skhurams** [comment]
disableAnimation: true
does not work

**Comment by initialxy** [comment]
You seem to have ran into the [issue you got before](https://github.com/initialxy/cordova-plugin-themeablebrowser/issues/7). How did you get it to work last time? This seems like a Cordova bug that it fails to install plugin properly every time you perform an update.

One thing I do want to point out is that there are **two** [config.xml](http://docs.phonegap.com/en/4.0.0/config_ref_index.md.html). One is more obvious than the other but that's no the one where plugin entry need to be added. There's a top level `config.xml` located at

    <cordova_project_root>/config.xml

This is **not** the one where plugin entry is added but it shows up right under your project in your Xcode. The one you need to look into is at 

    <cordova_project_root>/platforms/ios/<project_name>/config.xml

Which interestingly is hidden under `Staging` group in Xcode. Please take a look at that.
