### ISSUE TITLE
Not getting anything other than a blank toolbar

### ISSUE THREAD

**Issue by RobiFerentz** [initialxy/cordova-plugin-themeablebrowser#93]
No matter the configuration options I pass into the 'open' function, all I get is blank toolbar. Color does not affect it, showPageTitle does not affect it, nothing.

I'm testing this with an LG G3 Android 6 device.

**Comment by sencenan** [comment]
paste in your options pls

**Comment by RobiFerentz** [comment]
Sorry, managed to fix this on my end. Closing.
