### ISSUE TITLE
Is there a way to place customButtons before back/forward?

### ISSUE THREAD

**Issue by phoebusryan** [initialxy/cordova-plugin-themeablebrowser#99]
I wanna implement a custom button before the back/forward buttons and some other custombuttons after them. Is that possible? If not, can I place all custom buttons before back/forward buttons?

**Comment by phoebusryan** [comment]
Okay, I've got a solution. :-)

**Comment by phoebusryan** [comment]
Okay, I've got a solution. :-)

**Comment by vaibsVB** [comment]
@phoebusryan Can you plz share how you can achieve to add `Custom Buttons`.
Any help appreciated.

Thanks in advance.

**Comment by phoebusryan** [comment]
@vaibsVB No problem, it's very easy. look at my code here:
https://github.com/phoebusryan/phonegap_widderhotel/blob/master/js/index.js#L91-L146

Or... you can find information about it here, too:
https://github.com/initialxy/cordova-plugin-themeablebrowser
